version: '3.9'

services:
  db:
    container_name: mongo2 
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - ./dbdata:/app/dbdata 
  server:
    build: . 
    volumes:
      - ./src:/app/src 
    command: npm run dev 
    ports:
      - "8000:4000"
    depends_on:
      - db